### ISSUE TITLE
Interfacing BlackLab search to eXist.

### ISSUE THREAD

**Issue by pibburns** [earlyprint/earlyprint.github.io#11]
Look at ways to interface Blacklab searching with the eXist text display so matches can be displayed in context in eXist.  

Also look at ways to allow simple non-SQL seaches.   Those should be implementable by converting a simple "find this string" query to the equivalent CQL syntax on the fly.

Using BlackLab based searches requires that the eXist index and the BlackLab index be synchonized.  We'll need to find a workflow to automate that.

Once we have a good interface from eXist to Blacklab, we can dispense with the ineffective ngram search in eXist, which should significantly reduce the instances of index corruption which have put the EarlyPrint sites out of commission.

**Comment by craigberry** [comment]
This was completed here:

https://bitbucket.org/shcdemo/annopub/commits/40acf7ca47506244845ca8458f984828d10699fe
