### ISSUE TITLE
Requisition and configure epdev.at.earlyprint.org VM at Northwestern.

### ISSUE THREAD

**Issue by pibburns** [earlyprint/earlyprint.github.io#16]
VM requested.

**Comment by pibburns** [comment]
VM delivered and provisioned by Northwestern's cyberinfrastructure team.  

The software is currently being configured by Craig and Pib.

**Comment by craigberry** [comment]
In addition to completing certificate configuration, Apache proxy and rewrite rules, and some additional testing of eXist 5.0, we may want to do a conversion of NUPOS v2 to NUPOS v3 and reload the texts.  If Martin can provide a conversion table, one of us can do this without taking his time to do it, but we would then have texts consistent with what MorphAdorner is currently producing.

**Comment by martinmueller39** [comment]
I am planning to deliver the Phase I texts in the required format.  With some help from Craig I ccan probably integrate his final formatting rules into my scripts, which will make his life easier

**Comment by jrladd** [comment]
Shall I open a separate issue for the NUPOS v2 to v3 conversion, @craigberry?

**Comment by craigberry** [comment]
> Shall I open a separate issue for the NUPOS v2 to v3 conversion, @craigberry?

I would say no, since Martin is apparently already planning to do this.

**Comment by martinmueller39** [comment]
That’s right. I am working on this

**Comment by pibburns** [comment]
Ports 80 and 433 are now open on epdev.

**Comment by craigberry** [comment]
> On Nov 15, 2019, at 11:36 AM, pibburns <notifications@github.com> wrote:
> 
> Ports 80 and 433 are now open on epdev.

Thanks, I can confirm those work now.  There are no texts on epdev at the moment because something got corrupted and I ended up wiping the data directory and we'll be reloading everything soon.

Where do we stand on certificates renewals?

________________________________________
Craig A. Berry

"... getting out of a sonnet is much more
 difficult than getting in."
                 Brad Leithauser

**Comment by pibburns** [comment]
The current certs are good for about 22 more months, but only handle the northwestern.edu domain.  Now that epdev is working I will see if I can get certbot running on it.   If successful we can add the earlyprint.org domain to certbot-generated certs.

-- Pib


________________________________

**Comment by pibburns** [comment]
VM is configured and running, and is accessible as texts.earlyprint.org as well as its Northwestern domain name.   Certificate renewal should occur automatically.
