### ISSUE TITLE
Set up Twitter account and distribute login info

### ISSUE THREAD

**Issue by jrladd** [earlyprint/earlyprint.github.io#17]
As requested by @martinmueller39, I'm going to set up a Twitter account for us to share updates on the project.

The username earlyprint is unfortunately already taken. Some alternatives include:

- early_print (this one may still be unavailable, it's currently listed as "suspended" rather than unused)
- early-print (most people on Twitter don't use hyphens in usernames)
- earlymodernprint
- earlyprinting

If you have opinions, let me know!

**Comment by ABasu** [comment]
@early_print is what I set up. Twitter told me it was gone - but looks like they are blocking the handle for the time being.

**Comment by ABasu** [comment]
Hold on a bit and let me see if the handle can be released.

**Comment by ABasu** [comment]
Seems to be sorted. Everybody follow @early_print on Twitter. John will maintain the a/c. Yay!

**Comment by jrladd** [comment]
Hooray!

**Comment by jrladd** [comment]
Unfortunately, I have to reopen this. @ABasu I can log in just fine, but when I try to change anything it tells me the account is suspended.

**Comment by ABasu** [comment]
Yes. When you try to follow someone it'll throw an error and give you a link detailing how to get it unsuspended. Take a look and see if there's anything we need to do. I'll try later as well.

**Comment by ABasu** [comment]
Appeal filed with Twitter.

**Comment by ABasu** [comment]
Unlocked. John, take it for a spin and let me know.

**Comment by jrladd** [comment]
Great, I noticed the account followed me! I’ll get it all set up with
images and bio soon.

**Comment by ABasu** [comment]
John has set up the account. Everyone who's on Twitter please follow and occasionally retweet so we can get the word out!
