### ISSUE TITLE
Get everyone access to this Issues page

### ISSUE THREAD

**Issue by jrladd** [earlyprint/earlyprint.github.io#2]
Please comment on this issue once you have access to this page. Once I've received a comment from everyone I will begin entering issues for us to track.

**Comment by dknoxwu** [comment]
Thanks, John.

**Comment by spenteco** [comment]
Cool.  Thanks!

**Comment by pibburns** [comment]
Pib is watching.

**Comment by craigberry** [comment]
I'm watching.

**Comment by ABasu** [comment]
Yup!

**Comment by ABasu** [comment]
Send Joe a reminder or set him up with Github?

**Comment by jrladd** [comment]
Yes, I’ll do this, though he may not have a chance until he’s back from the
Knox visit.
