### ISSUE TITLE
Is the current background image too dominant?

### ISSUE THREAD

**Issue by martinmueller39** [earlyprint/earlyprint.github.io#21]
I spent much of yesterday with the Annotation Module reviewing student work and generally cleaning up a bit. I have a mixed response to the current visuals. On the one hand they are striking and direct attention to what we are about. On the other hand, they may be too intrusive. I found myself  confused at times looking at the text page or the image page: they sometimes look dwarfed by the surrounding background. That may be just me getting used to a new view, or it may be more.  Compare the German Text Archive (http://www.deutschestextarchiv.de/book/view/bebel_sozialdemokratie_1895?p=10) where you wouldn't be likely to have such an impression. 
Wouldl some user testing be helpful?

**Comment by craigberry** [comment]
Martin,



What site were you using to review and clean up things?  If you were on eptexts, which I assume you were given your comments about the background picture, the annotations there were loaded by restoring a backup from production a while back for testing purposes.  It will be wiped and replaced with a fresh copy from production when we migrate servers.  If you did a lot of work, I guess I can try to rescue it, but it will be very hard to distinguish new work from old work that may now be in a different state on the production server.



Several people have spent a lot of time in the last couple of weeks getting the new design consistent and I would argue against any major changes to it without a very clear plan and consensus on what we're aiming for.  There may be some relatively minor tweaks that can be done, such as wrapping an opaque div around the side-by-side text and image so the background picture is, well, more in the background.


On November 6, 2019 at 8:39 AM, martinmueller39 <notifications@github.com> wrote:



I spent much of yesterday with the Annotation Module reviewing student work and generally cleaning up a bit. I have a mixed response to the current visuals. On the one hand they are striking and direct attention to what we are about. On the other hand, they may be too intrusive. I found myself confused at times looking at the text page or the image page: they sometimes look dwarfed by the surrounding background. That may be just me getting used to a new view, or it may be more. Compare the German Text Archive (http://www.deutschestextarchiv.de/book/view/bebel_sozialdemokratie_1895?p=10) where you wouldn't be likely to have such an impression.
Wouldl some user testing be helpful?

**Comment by martinmueller39** [comment]
I didn’t make any changes on the site but just used it to check stuff on my list. All changes I’m making right now are made on my machine and put into the texts from which the new Phase I texts will be updated.

**Comment by jrladd** [comment]
I had been wondering the same thing about the prominence of the background image. I tested having it be less bright (or having the lines be less dark? the terminology is confusing), but I couldn't get it to work quite right.

I like the idea of wrapping the text and image sections in an opaque div. That's the place where I think the background becomes most distracting, and it doesn't require a lot of rethinking of the design elsewhere.

**Comment by martinmueller39** [comment]
I don’t know what the right solution is, but in an application that serves up texts readability is king.

**Comment by ABasu** [comment]
Link to the annotation module with the new background?

**Comment by craigberry** [comment]
On November 6, 2019 at 11:15 AM, Anupam Basu <notifications@github.com> wrote:



Link to the annotation module with the new background?

https://eptexts.at.northwestern.edu



I have a couple other changes in progress related to sticky hover colors that aren't there yet.

**Comment by craigberry** [comment]
I have updated the background on the Browse page to mute the background picture by putting both text and image in a transparent (but not very transparent) wrapper.

**Comment by martinmueller39** [comment]
That’s definitely an improvement

**Comment by craigberry** [comment]
I've made some additional tweaks to the style of the eXist app and I think it's working reasonably well, perhaps even better than with the previous design, so I'm going to go ahead and close this item.  Obviously the interface will never be perfect and we can open additional tickets as we discover additional points of friction.

**Comment by martinmueller39** [comment]
It looks pretty good to me, and definitely good enough to work with it for a while.
