### ISSUE TITLE
update

### ISSUE THREAD

**Issue by martinmueller39** [earlyprint/earlyprint.github.io#24]
Here is what I'm planning to do this weeK:  we want to push out a version of TCP Phase 1 on the NU servers and hope that this will be a good enough solution through much of next year. I will create a version of the texts that use the NUPOS 3 tags.  These are renamed to make editing easier. They are not redefined, with the exception of a new 'nnp' tag that captures 'le', 'de', etc when they are part of names. 

Before doing this I want to reread through the 50,000 most common combinations of a spelling, pos tag, lemma, and regular spelling in texts before 1640--basically the STC texts.  Roughly speaking, these are spellings that occur at least 250 times in texts before 1640, and they add up to 96% of all tokens. Reading through lists like that without context is an efficient way of catching crude errors and replacing them with corrections that may be right but are certainly less wrong. A spelling that occurs 250 times in texts before 1640 has a lower relative frequency than a spelling that occurs once in the Shakespeare canon. 

With luck I'll finish this week

**Comment by jrladd** [comment]
Will these new texts also replace the current Bitbucket texts?

**Comment by martinmueller39** [comment]
Yes

**Comment by craigberry** [comment]
These texts have been on BitBucket and in the eXist app for some time.
