### ISSUE TITLE
splashpage and background

### ISSUE THREAD

**Issue by martinmueller39** [earlyprint/earlyprint.github.io#26]
My skepticism about the current background has deepened.  It's not a matter of how pale, but a matter of a quasi-realistic picture that is covered up and creates an unpredictable variety of different combinations of overlay and underlay and end up distracting the user.  The image, however, is appropriate. What about a landing page that is vertically divided with the image on the left--like a frontispiece-- and the current text on the right.  There might a sentence at the bottom that says: Work on EarlyPrint has been generously supported by several grants from the Mellon Foundation and the American Council of Learned Societies.

**Comment by jrladd** [comment]
I just spoke to the WashU folks about this, and while they'd like to keep the background on some of the pages where it's less intrusive, we agreed that it's too much on the Annotation Module pages. Tagging @jfloewen in case he'd like to say more.

@craigberry, could we simply remove the background image entirely from the Library site? We could just use a plain white background instead, or a light gray.

**Comment by craigberry** [comment]
> On Dec 3, 2019, at 4:47 PM, JR Ladd <notifications@github.com> wrote:
> 
> @craigberry, could we simply remove the background image entirely from the Library site? We could just use a plain white background instead, or a light gray.

I have removed the background image.  A plain white background feels like being under interrogation with bright lights shining in your eyes.  A light gray background feels rather dismal, like your color TV is broken and can display only black and white.  As yet another alternative, I have taken a tiny slice of the paper from the previous background image and set it as a repeating pattern.  You can see what it looks like here:

<https://eptexts.at.northwestern.edu/>

If you still see the press image, clear your browser cache and try again.  

I suspect everyone will hate it as much as the last three designs but for different reasons.  It would certainly be much better if it started from a high resolution image of actual early modern paper.  Most things I have in that category are much darker, which I don't think would contrast sufficiently with the ink-colored header, so if you have something more appropriate, do send it along.  The repeating pattern does make it look a bit like laid paper; maybe something from <https://collation.folger.edu/2012/06/learning-to-read-old-paper/> would work.

________________________________________
Craig A. Berry

"... getting out of a sonnet is much more
 difficult than getting in."
                 Brad Leithauser

**Comment by martinmueller39** [comment]
I’m happier. There is a design problem that may be a hard-coded feature of the Annotation Module. If you’re just reading the text and there is no available half the screen is empty and stares at you. If you use the AM some of it is used, but there still is a lot of empty space.  One could imagine a solution in which the space on the right exists only to the extent that it is used. But I’m not sure whether it’s worth throwing time at it.  Fake linen paper might be nice…

**Comment by martinmueller39** [comment]
Having just spent a couple of hours looking at the screen of the EarlyPrint I can say with great conviction that it is much less distracting and much simpler to work with.

**Comment by craigberry** [comment]
I have made another attempt with a laid paper background that is more on the gray side and matches the ink-colored header better.  Snippet attached, or visit <https://eptexts.at.northwestern.edu/>.  It may well be too much gray for some people and not enough something else for others.  This does not preclude leaving the press image as-is for the main earlyprint.org page, but if we ever agree on a background, I still think it would be nice to have the Library and Lab pages consistent with each other.

**Comment by martinmueller39** [comment]
I’m partial to gray. Phil, I think, isn’t. I’m not passionate on this, but am passionate about the solution that for most people will get least in the way of reading the text.

**Comment by craigberry** [comment]
We've been living with the laid paper background for some months and I have not heard further complaints.
