### ISSUE TITLE
Create workflow for standalone epub and pdf generation from TEI texts.

### ISSUE THREAD

**Issue by pibburns** [earlyprint/earlyprint.github.io#6]
We want to pregenerate epubs and PDFs from the EarlyPrint TEI files so that these do not need to be generated on the fly.

The standard TEI consortium scripts for generating epubs from TEI files work well enough.   Their output is not as attractive as that produced by our code within eXist.   We can probably improve the appearance.

The free Calibre suite now does a good job of converting epubs to pdf files.  Calibre is a free program and works on Windows, Linux,and Mac OSX.  Calibre can also generate other formats such as kindle, although if we decide to generate kindle versions, the standard (free) Amazon software is probably a better choice.

Pregenerating the ebook versions of the texts obviates the need for repeated on-demand generation of such versions.  We will want to create both original and standardized spelling versions, as we currently provide now.  We also want to update the ebooks whenever the TEI versions of the EarlyPrint texts change.

**Comment by martinmueller39** [comment]
Would it make sense to make sample versions of half a dozen different files and run them by our Early Modernists to see what they like or don’t like?

Related to this issue is pdfs of standard spellings, which some user might like.

**Comment by pibburns** [comment]
> 
> Would it make sense to make sample versions of half a dozen different files and run them by our Early Modernists to see what they like or don’t like? Related to this issue is pdfs of standard spellings, which some user might like. 

If you provide me a list of texts, I will generate the barebones epubs and matching pdfs.   I can store the results in a Box folder for folks to peruse.

**Comment by craigberry** [comment]
We've been doing what Phil suggested for a couple years now.  The code that does it is here:

https://bitbucket.org/eplib/downloads/src/master/
