### ISSUE TITLE
Move Northwestern-produced image sets to main Northwestern IIIF server.

### ISSUE THREAD

**Issue by pibburns** [earlyprint/earlyprint.github.io#7]
The Northwestern University Library produced the page images for a number of texts in the EarlyPrint collection.   Currently these are served from a small underpowered virtual server.

I will work with the Northwestern Library IT staff to move these images to the main Northwestern IIIF server.  Once those text images are available from Northwestern's server, we can edit the image references in the TEI texts to point to that server.  In parallel, we can revise the existing image references for texts which have images in the Internet Archive to point to the Internet Archive editions of the texts.

**Comment by craigberry** [comment]
imageserver.earlyprint.org has been for about a year now an alias for classify.ci.northwestern.edu, a new RHEL 8 machine running Cantaloupe.  Whatever Phil was planning with the NU Library didn't happen, but this solution seems to be working well enough for now.

**Comment by craigberry** [comment]
Closing.
