### ISSUE TITLE
Apply all outstanding corrections to TEI texts.

### ISSUE THREAD

**Issue by pibburns** [earlyprint/earlyprint.github.io#8]
There are a number of correction which have not been applied to the EarlyPrint texts.  Many of these require partial readornment of the affected words and surrounding words.  That is turn required quite a few changes to MorphAdorner to deal with changes in the NUPos part of speech tag set as well as changes in the format for generating word IDs.

**Comment by craigberry** [comment]
> On Oct 12, 2019, at 3:40 PM, pibburns <notifications@github.com> wrote:
> 
> There are a number of correction which have not been applied to the EarlyPrint texts. Many of these require partial readornment of the affected words and surrounding words. That is turn required quite a few changes to MorphAdorner to deal with changes in the NUPos part of speech tag set as well as changes in the format for generating word IDs.

There is some basic documentation of the annotation format in the README for the annotation service here:

<https://bitbucket.org/shcdemo/annotation-service/src/master/>



________________________________________
Craig A. Berry

"... getting out of a sonnet is much more
 difficult than getting in."
                 Brad Leithauser

**Comment by pibburns** [comment]
All outstanding corrections, except those related to missing chunks which were not transcribed, have been applied as of 1019/12/12.
